### ISSUE TITLE
Installing on Windows 10 problems

### ISSUE THREAD

**Issue by delebash** [jkirsons/FacialMotionCapture#3]
I know you have a version specifically for Windows without dlib but as you stated it is not as good as the dlib version.  I was able to install dlib for python 3.6 as described https://pysource.com/2019/03/20/how-to-install-dlib-for-python-3-on-windows/

dlib installed sucessfully using python 3.6.  I think the problem I am having is that Blender 2.82a uses python 3.7 that is include in the blender install.  I tried setting my environmental paths to point to python 3.6 but it seems blender is still using 3.7 where no modules are installed.   Any help would be appreciated.

Thanks

**Comment by ksiv** [comment]
I m not a python fan myself, but when I needed this project to work I  hacked it using conda. Installed it in parallel it has compiler and all build tools in place and correctly configured (Unlike Windows Python or any other python). So I made with it a WHL and installed this whl into all my pythons.

**Comment by delebash** [comment]
Thanks

**Comment by lucasjinreal** [comment]
I met same problem:

![image](https://user-images.githubusercontent.com/21303438/147909882-b9bd2812-0ea9-4c98-95be-a89efb3bf0a4.png)


dlib installed,

but can not import:


![image](https://user-images.githubusercontent.com/21303438/147909904-0deffd86-8f79-416f-8053-a9b939c79b43.png)
